name: npm-ci
author: 'Peter Jokumsen'
description: 'Install npm dependencies or use cached dependencies'

inputs:
  working-directory:
    description: 'Working directory to use'
    default: './'

runs:
  using: 'composite'
  steps:
    - shell: pwsh
      run: |
        Write-Output "::warning title=action deprecated::use chill-viking/npm-ci@latest instead, working-directory input changed to working_directory"

    - name: Use node_modules from cache [npm]
      id: cache-nodemodules
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        # caching node_modules
        path: ${{ inputs.working-directory }}node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - shell: pwsh
      name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: |
        npm ci

    - shell: pwsh
      name: Check path for cache
      run: |
        if (Test-Path ${{ inputs.working-directory }}node_modules)
        {
          Write-Output "node_modules found, will be cached"
        }
        else
        {
          Write-Output "::warning title=node_modules not found::node_modules not found using path '${{ inputs.working-directory }}'"
        }
