on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory nx workspace is found in, defaults to root'
        default: './'
      fetch-depth:
        description: 'Fetch depth to use for checkout, defaults to 5'
        default: 5
      agent-count:
        description: 'Number of agents to be used, defaults to 3'
        default: 3

name: Lint, Test, and Build Affected

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-workspace:
    name: Nx Lint Workspace
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v3

      - name: Lint Workspace
        run: npx nx-cloud record -- npx nx workspace-lint

  lint-test-build:
    strategy:
    matrix:
      target:
        - lint
        - test
        - build
    name: 'Nx Affected: ${{ matrix.target }}'
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - uses: chill-viking/actions/npm-ci
        name: Install dependencies w/ caching
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Run Target
        run: npx nx affected --target=${{ matrix.target }} --parallel=${{ inputs.agents }}
