on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory nx workspace is found in, defaults to root'
        default: './'
        type: string
      fetch-depth:
        description: 'Fetch depth to use for checkout, defaults to 5'
        default: 0
        type: number
      agent-count:
        description: 'Number of agents to be used, defaults to 3'
        default: 3
        type: number
      base:
        description: 'Base to compare, defaults to origin/main'
        default: 'origin/main'
        type: string
      head:
        description: 'Target to compare, defaults to HEAD'
        default: 'HEAD'
        type: string

name: Lint, Test, and Build Affected

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-workspace:
    runs-on: ubuntu-latest
    name: Nx Lint Workspace
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v3

      - uses: chill-viking/workflows/actions/npm-ci@main
        name: Install dependencies w/ caching
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Lint Workspace
        run: npx nx-cloud record -- npx nx workspace-lint

  lint-test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - lint
          - test
          - build
    name: 'Nx Affected: ${{ matrix.target }}'
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - uses: chill-viking/workflows/actions/npm-ci@main
        name: Install dependencies w/ caching
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Run Target ${{ matrix.target }}
        run: |
          $expression=@(
            'npx nx affected'
            '--target=${{ matrix.target }}'
            '--parallel=${{ inputs.agent-count }}'
            '--base=${{ inputs.base }}'
            '--head=${{ inputs.head }}'
          ) -join ' '
          echo $expression
          Invoke-Expression $expression
